### PR TITLE
Adapt to explicit specificity

### LINKED ISSUE #81: Adapt to explicit specificity
GHC 8.12's version of `template-haskell` will ship with support for [explicit specificity](https://gitlab.haskell.org/ghc/ghc/-/commit/a9311cd53d33439e8fe79967ba5fb85bcd114fec). This changes `TyVarBndr` to add another type parameter, since type variable binders now have the possibility of being specified (e.g., `forall a.`), inferred (e.g., `forall {a}.`), or neither (in places where specificity is irrelevant, such as in the type variable binders in `data D a b`). Unsurprisingly, `th-abstraction` will need to adapt to these changes. The tricky part is figuring out a good way to do so.

I wrote a quick-and-dirty `th-abstraction` patch for `head.hackage` [here](https://gitlab.haskell.org/ghc/head.hackage/-/blob/ca9ca8b284ed2736bd78c89649cef508e308ba7c/patches/th-abstraction-0.3.2.0.patch), which introduces various compatibility shims. One thing that is a bit unsatisfying about this patch is that I end up needing to redefine these shims in other libraries that use `th-abstraction`, (e.g., [in `lens`](https://gitlab.haskell.org/ghc/head.hackage/-/blob/ca9ca8b284ed2736bd78c89649cef508e308ba7c/patches/lens-4.19.2.patch#L107-136)). To avoid this, I would propose that we introduce a new `Language.Haskell.TH.Datatype.TyVarBndr` module to `th-abstraction` whose sole purpose is to provide various `TyVarBndr`-related shims for other libraries to use. This would include:

* `TyVarBndr_`, `TyVarBndrSpec`, and `TyVarBndrUnit`:

  ```hs
  #if MIN_VERSION_template_haskell(2,17,0)
  type TyVarBndr_ spec = TyVarBndr_ spec
  -- template-haskell already defines TyVarBndrSpec and TyVarBndrUnit
  #else
  type TyVarBndr_ spec = TyVarBndr
  type TyVarBndrSpec   = TyVarBndr
  type TyVarBndrUnit   = TyVarBndr
  #endif
  ```
* `elimtV`, which provides a way to "pattern-match" on `PlainTV`s and `KindedTV`s without the use of CPP:

  ```hs
  elimTV :: (Name -> r) -> (Name -> Kind -> r) -> TyVarBndr_ spec -> r
  ```
* Backwards-compatible ways to construct `PlainTV`s and `KindedTV`s:

  ```hs
  plainTV      :: Name -> TyVarBndrUnit
  kindedTV     :: Name -> Kind -> TyVarBndrUnit
  plainTVSpec  :: Name -> Specificity -> TyVarBndrSpec
  kindedTVSpec :: Name -> Specificity -> Kind -> TyVarBndrSpec
  ```
* Functions for mapping over `TyVarBndr`s:

  ```hs
  mapTyVarBndr :: (Name -> Name) -> (spec -> spec) -> (Kind -> Kind)
               -> TyVarBndr_ spec -> TyVarBndr_ spec
  traverseTyVarBndr :: Applicative f
                    => (Name -> f Name) -> (spec -> f spec) -> (Kind -> f Kind)
                    -> TyVarBndr_ spec -> f (TyVarBndr_ spec)
  ```
* `changeSpecs`, a function for changing the specificity of a list of `TyVarBndr`s:

  ```hs
  changeSpecs :: newSpec -> [TyVarBndr_ oldSpec] -> [TyVarBndr_ newSpec]
  ```

  This is particularly useful in situations where you need to re-use `TyVarBndr`s bound by, say, a `DataD` in a `ForallT` (or vice versa):

  ```hs
  case x of
    DataD _ _ tvbs _ _ _ ->
      ForallT (changeSpecs SpecifiedSpec tvbs) ...
  ```
* Possibly others that I am overlooking right now.

### LINKED ISSUE #82: Fails to build against GHC HEAD
I'm getting this error:

```
src/Language/Haskell/TH/Datatype.hs:217:31: error:
    • Expecting one more argument to ‘TyVarBndr’
      Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’
    • In the type ‘[TyVarBndr]’
      In the definition of data constructor ‘ConstructorInfo’
      In the data declaration for ‘ConstructorInfo’
    |
217 |   , constructorVars       :: [TyVarBndr]        -- ^ Constructor type parameters
    |                               ^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
This patch adapts `th-abstraction` to `template-haskell-2.17.0.0`, which adds a `flag` type parameter to `TyVarBndr`. This makes it especially difficult to support pre-2.17.0.0 versions of `template-haskell` without obnoxious amounts of CPP, so to make things slightly more tolerable, this patch also introduces a new `Language.Haskell.TH.Datatype.TyVarBndr` module. The purpose of this module is to define various type synonyms and utility functions that make it possible to write CPP-free code involving `TyVarBndr`s.

Fixes #81. Fixes #82.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
@phadej will likely be interested in this PR. Some questions that he might have an opinion on:

* This introduces a compatibility module, `Language.Haskell.TH.Datatype.TyVarBndr`. There are many potential libraries that this could live in, but I somewhat arbitrarily chose `th-abstraction` as its home since it uses `TyVarBndr`s so heavily (as will any library that depends on `th-abstraction`, most likely). What is the right home for it?
* Should this change demand a major version bump at all? Technically speaking, the only version of `template-haskell` that will be affected by these changes is `template-haskell-2.17.0.0` (which hasn't officially been released yet). Still, it's quite likely that people will need to change their code their code to adapt to `template-haskell-2.17.0.0` anyway, and the major version bump for `th-abstraction` signals that.
* Are there any other `TyVarBndr` utility functions that we should define? The functions that I've defined currently handle most of my use cases, but there might be other interested use cases that I haven't thought about yet.

File: src/Language/Haskell/TH/Datatype.hs [hunk 1]
```diff
@@ -178,16 +179,16 @@ import           Data.Monoid (Monoid(..))
...
+--                         , 'KindedTV' f () 'StarT'
+--                         , 'KindedTV' x () 'StarT' ]
 --   'datatypeInstTypes' = [ 'AppT' ('ConT' ''Maybe) ('VarT' c)
 --                         , 'AppT' ('VarT' f) ('VarT' x) ]
 --   @
 data DatatypeInfo = DatatypeInfo
   { datatypeContext   :: Cxt               -- ^ Data type context (deprecated)
   , datatypeName      :: Name              -- ^ Type constructor
-  , datatypeVars      :: [TyVarBndr]       -- ^ Type parameters
+  , datatypeVars      :: [TyVarBndrUnit]   -- ^ Type parameters
```
Comment (phadej) [inline src/Language/Haskell/TH/Datatype.hs:191]: This is breaking change, so yes, major bump is fine. Personally I have bounds on `template-haskell`, so if I need to relax / update  `th-abstraction` bounds at the same time, it's not biggie.

**Comment by phadej** [comment]
I think `th-abstraction` is fine for new functionality. `DatatypeInfo` is `th-abstraction` thing, so having nice api to deal with it in `th-abstraction` makes sense. (It would have to be re-exported, I guess, if it where somewhere else).

**Comment by RyanGlScott** [comment]
GHC 9.0.1-alpha1 is now out, and I have verified that this PR compiles and passes the test suite with it. Since releasing this will be a prerequisite for porting many other libraries over to support GHC 9.0, I'm keen on releasing a new version of `th-abstraction` soon with these changes. @glguy, do you have any review comments before I land this?

**Review by glguy — APPROVED** [review]
While I haven't been following the changes to GHC's type variables closely I did read through these changes and what I saw makes sense; I didn't find anything surprising along the way.
