### PR TITLE
Fix #1 (take two)

### LINKED ISSUE #1: Breaks on data families in GHC 7.8 due to eta-reduction bug
```
λ> :set -XTypeFamilies -XTemplateHaskell 
λ> import Language.Haskell.TH.Datatype 
λ> data family Foo a
λ> newtype instance Foo a = MkFoo a
λ> putStrLn $(reifyDatatype 'MkFoo >>= stringE . show)

<interactive>:7:12:
    Impossible free variable: a_1627419361
    In the splice: $(reifyDatatype 'MkFoo >>= stringE . show)
```

This happens due to a GHC 7.8-specific bug that causes eta-reduced type variables in data family instances (such as the `a` in `MkFoo a`) not to appear when you reify them in Template Haskell.

On GHC 7.8.4 (broken):

```
λ> putStrLn $(reify ''Foo >>= stringE . pprint)
data family Ghci1.Foo a_0 :: *
newtype instance Ghci1.Foo = Ghci2.MkFoo a_1
```

On GHC 8.0.2 (working):

```
λ> putStrLn $(reify ''Foo >>= stringE . pprint)
data family Ghci1.Foo a_0 :: *
newtype instance Ghci1.Foo = Ghci2.MkFoo a_1
```

I have a workaround in place that I use in `bifunctors`, `aeson`, and other libraries. I'll look into porting it over to `th-abstraction` as well.

### PR DESCRIPTION
**Pull request by RyanGlScott**
An improvement upon #4. This fixes the eta-reduction bug for data families encountered on GHC 7.6 and 7.8, and properly takes into account `PolyKinds` and `GADTs`.

This approach differs from the current one in that we don't take type variables from the _constructor_ type's `TyVarBndr`s anymore. Instead, we take them from the _parent data family_ `TyVarBndr`s, and do the appropriate alpha-renaming for each constructor. This has the downside that the extra type variables might have different names than they otherwise would have, but this is the only approach that is guaranteed to work in the presence of GADTs, which can yield constructor types with more/fewer `TyVarBndr`s than the data family instance itself.

Fixes #1.

### CODE REVIEW

File: src/Language/Haskell/TH/Datatype.hs [hunk 1]
```diff
@@ -316,37 +317,120 @@ normalizeDec' context name params cons variant =
...
+-- the type and parameters of the constructor, as well as whether the constructor
+-- is for a data family instance, as extracted from the outer
 -- 'Dec'.
 normalizeCon ::
-  Name   {- ^ Type constructor -} ->
-  [Type] {- ^ Type parameters  -} ->
-  Con    {- ^ Constructor      -} ->
+  Name            {- ^ Type constructor  -} ->
+  [Type]          {- ^ Type parameters   -} ->
+  DatatypeVariant {- ^ Extra information -} ->
```
Comment (RyanGlScott) [inline src/Language/Haskell/TH/Datatype.hs]: It's a bit unfortunate I had to change the public API here to account for this eta-reduction bug, but I don't see a cleaner way to tell if we're in a data family instance or not within `normalizeCon`. We could re-do all of the work in `normalizeDec`, but that feels rather gross...

File: src/Language/Haskell/TH/Datatype.hs [hunk 2]
```diff
@@ -316,37 +317,120 @@ normalizeDec' context name params cons variant =
...
+                -- Con argument above, as they might be scoped over eta-reduced
+                -- variables. Instead of trying to figure out what the
+                -- eta-reduced variables should be substituted with post facto,
+                -- we opt for the simpler approach of using the context and
+                -- argument types from the reified constructor Info, which will
+                -- at least be correctly scoped. This will make the task of
+                -- substituting those types with the variables we put in
+                -- place of the eta-reduced variables (in normalizeDec)
+                -- much easier.
+                normalizeGadtC typename params tyvars context [n]
```
Comment (RyanGlScott) [inline src/Language/Haskell/TH/Datatype.hs]: This `normalizeGadtC` function came in handy here! However, it might be a bit inappropriately named now, since here it's being used on things that aren't necessarily GADTs.
